version: "3.8"

services:
# ---------------------------- Discord ----------------------------
    discord:
        build:
            context: discord
            dockerfile: Dockerfile
        container_name: discord
        environment:
            - DISCORD_TOKEN
            - KAFKA_SERVER=kafkaserver:29092
        volumes:
            - ./logs:/usr/share/logs
            - ./discord/scripts:/app
        networks:
            - tap

# ---------------------------- logstash ----------------------------
    logstash:
        build:
            context: logstash
            dockerfile: Dockerfile
        container_name: logstash
        environment:
            - KAFKA_SERVER=kafkaserver:29092
            - ELASTIC_SERVER=elasticsearch:9200
        volumes:
            - ./logs:/usr/share/logs
        networks:
            - tap

# ---------------------------- kafka ----------------------------
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - tap

    kafkaserver:
        image: confluentinc/cp-kafka:7.0.1
        container_name: kafkaserver
        hostname: kafkaserver
        ports:
            - "29092:29092"
            - "9092:9092"
            - "9101:9101"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafkaserver:29092
            KAFKA_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafkaserver:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        networks:
            - tap

    webui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            KAFKA_CLUSTERS_0_NAME: my_cluster
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaserver:29092
        ports:
            - 8080:8080
        depends_on:
            - kafkaserver
        networks:
            - tap


# ---------------------------- spark ----------------------------
    spark:
        build:
            context: spark
            dockerfile: Dockerfile
        ports:
            - 4040:4040
        environment:
            - ORGANIZATION
            - OPENAI_API_KEY
            - ELASTIC_INDEX=tap
            - ENGINE=text-davinci-002
            - KAFKA_SERVER=kafkaserver:29092
            - TOPIC_IN=chat-log
            - TOPIC_DISCORD=send-to-discord
        container_name: spark
        depends_on:
            - kafkaserver
        volumes:
            - ./logs:/usr/share/logs
            - ./spark/scripts:/app
        networks:
            - tap


# ---------------------------- elasticsearch ----------------------------
    elasticsearch:
        image: elasticsearch:7.9.2
        container_name: elasticsearch
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - tap

# ---------------------------- kibana ----------------------------
    kibana:
        image: kibana:7.9.2
        container_name: kibana
        ports:
            - '5601:5601'
        networks:
            - tap
volumes:
    logs:
networks:
    tap:
        name: tap
        driver: bridge
