version: "3.8"

services:
# ---------------------------- Discord ----------------------------
    discord:
        build:
            context: discord
            dockerfile: Dockerfile
        container_name: discord
        volumes:
            - ./logstash/json:/usr/share/logstash/json
            - ./discord:/app
        networks:
            - tap

# ---------------------------- logstash ----------------------------
    logstash:
        build:
            context: logstash
            dockerfile: Dockerfile
        container_name: logstash
        volumes:
            - ./logstash/json:/usr/share/logstash/json
        networks:
            - tap

# ---------------------------- kafka ----------------------------
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - tap

    kafkaserver:
        image: confluentinc/cp-kafka:7.0.1
        container_name: kafkaserver
        hostname: kafkaserver
        ports:
            - "9092:9092"
            - "9093:9093"
            - "9101:9101"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 0
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaserver:9092,PLAINTEXT://kafkaserver:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        networks:
            - tap

    webui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            KAFKA_CLUSTERS_0_NAME: my_cluster
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaserver:9092
        ports:
            - 8080:8080
        depends_on:
            - kafkaserver
        networks:
            - tap


# ---------------------------- spark ----------------------------
    spark:
        build:
            context: spark
            dockerfile: Dockerfile
        environment:
            OPENAI_API_KEY: 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
        ports:
            - 4040:4040
        container_name: spark
        depends_on:
            - kafkaserver
        volumes:
            - ./logstash/json:/usr/share/logstash/json
            - ./spark/scripts:/app
        networks:
            - tap


# ---------------------------- elasticsearch ----------------------------
    elasticsearch:
        image: elasticsearch:7.9.2
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        mem_limit: 4g
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - tap

# ---------------------------- kibana ----------------------------
    kibana:
        image: kibana:7.9.2
        ports:
            - '5601:5601'
        networks:
            - tap
        mem_limit: 1g
volumes:
    json:
networks:
    tap:
        name: tap
        driver: bridge
